# Generated by Django 4.2.5 on 2023-09-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(max_length=200)),
                ('schedules', models.CharField(max_length=200)),
            ],
        ),
    ]
