# Generated by Django 4.2.5 on 2023-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_application_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(max_length=30, verbose_name='Тип')),
                ('week_days', models.CharField(max_length=200, verbose_name='Дни недели')),
                ('lessons_counts', models.CharField(max_length=50, verbose_name='Уроков в день')),
                ('week_type', models.CharField(max_length=200, verbose_name='Тип недели')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
