# Generated by Django 4.2.5 on 2023-09-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_schedules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
