# Generated by Django 4.2.5 on 2023-09-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_delete_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('seat_number', models.CharField(max_length=50, verbose_name='Количество мест')),
                ('building', models.CharField(max_length=50, verbose_name='Корпус')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cabinets', to='users.applications')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('cabinets', models.CharField(max_length=50, verbose_name='Аудитории')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='users.applications')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='WorkLoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Предмет')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('teacher', models.CharField(max_length=50, verbose_name='Преподаватель')),
                ('cabinet', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('lessons', models.CharField(max_length=50, verbose_name='Уроков')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkLoads', to='users.applications')),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузки',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Преподаватель')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('cabinets', models.ManyToManyField(to='applications.cabinets')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teachers', to='users.applications')),
                ('subjects', models.ManyToManyField(to='applications.subjects')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('week_date', models.DateField(verbose_name='Дата')),
                ('week_days', models.CharField(max_length=50, verbose_name='Дни недели')),
                ('lessons_counts', models.CharField(max_length=50, verbose_name='Уроков в день')),
                ('week_type', models.CharField(max_length=50, verbose_name='Тип недели')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedules', to='users.applications')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('students_count', models.CharField(max_length=50, verbose_name='Количество учащихся')),
                ('cabinets', models.CharField(max_length=50, verbose_name='Аудитории')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups', to='users.applications')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
