# Generated by Django 4.2.5 on 2023-09-14 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_delete_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('seat_number', models.CharField(max_length=50, verbose_name='Количество мест')),
                ('building', models.CharField(max_length=50, verbose_name='Корпус')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cabinets', to='users.applications')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('students_count', models.CharField(max_length=50, verbose_name='Количество учащихся')),
                ('cabinets', models.CharField(max_length=50, verbose_name='Аудитории')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groups', to='users.applications')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('week_date', models.DateField(verbose_name='Дата')),
                ('lessons_counts', models.CharField(max_length=50, verbose_name='Уроков в день')),
                ('week_type', models.CharField(max_length=50, verbose_name='Тип недели')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_applications', to='users.applications')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('cabinets', models.CharField(max_length=50, verbose_name='Аудитории')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='users.applications')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Преподаватель')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Сокращение')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teachers', to='users.applications')),
                ('cabinets', models.ManyToManyField(to='applications.cabinets')),
                ('subjects', models.ManyToManyField(to='applications.subjects')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='WorkLoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_count', models.PositiveIntegerField()),
                ('cabinets', models.ManyToManyField(to='applications.cabinets')),
                ('groups', models.ManyToManyField(to='applications.groups')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='applications.schedules')),
                ('subjects', models.ManyToManyField(to='applications.subjects')),
                ('teachers', models.ManyToManyField(to='applications.teachers')),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузки',
            },
        ),
        migrations.AddField(
            model_name='schedules',
            name='week_days',
            field=models.ManyToManyField(to='applications.weekday'),
        ),
        migrations.CreateModel(
            name='Bells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=50, verbose_name='Урок')),
                ('time_start', models.TimeField(default=django.utils.timezone.now, verbose_name='Начало урока')),
                ('time_end', models.TimeField(default=django.utils.timezone.now, verbose_name='Конец урока')),
                ('week_day', models.CharField(max_length=50, verbose_name='День недели')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bells', to='applications.schedules')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
    ]
