# Generated by Django 4.2.5 on 2023-09-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_schedules'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_applications', to='users.applications'),
        ),
    ]
