# Generated by Django 4.2.5 on 2023-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_workloads_subjects_workloads_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonsCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
                ('cellName', models.CharField(max_length=50, verbose_name='Место')),
                ('dataElementId', models.ManyToManyField(to='applications.workloads')),
            ],
        ),
    ]
