# Generated by Django 4.2.5 on 2023-09-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_workloads_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloads',
            name='lessons_count',
            field=models.PositiveIntegerField(),
        ),
    ]
