# Generated by Django 4.2.5 on 2023-09-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_schedules_schedule_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
