# Generated by Django 4.2.5 on 2023-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_lessonscells'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonscells',
            name='group',
            field=models.CharField(default=1, max_length=50, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workloads',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
