# Generated by Django 4.2.5 on 2023-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_lessonscells_group_alter_workloads_lessons_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonscells',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Группа'),
        ),
    ]
