# Generated by Django 4.2.5 on 2023-09-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_schedule_id_cabinets_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='week_days',
        ),
        migrations.AddField(
            model_name='schedules',
            name='week_days',
            field=models.ManyToManyField(to='applications.weekday'),
        ),
    ]
