# Generated by Django 4.2.5 on 2023-12-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_lessonscells_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonscells',
            options={'verbose_name': 'Сетка уроков'},
        ),
    ]
