# Generated by Django 4.2.5 on 2023-12-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_lessonscells_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonscells',
            options={'verbose_name': 'Сетка уроков', 'verbose_name_plural': 'Сетки уроков'},
        ),
    ]
