# Generated by Django 4.2.5 on 2023-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_students_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='institution_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applications',
            name='schedules',
            field=models.CharField(max_length=200),
        ),
    ]
