# Generated by Django 4.2.5 on 2023-09-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_applications_institution_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Applicationss',
        ),
    ]
