# Generated by Django 4.2.5 on 2023-09-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_applications_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
